services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - "./db/:/var/lib/influxdb2:rw"
    ports:
      - "8086:8086"
  flask_server:
    build: server
  web:
    build: nginx
    ports:
      - "80:80"